### PR TITLE
Update tor version to 0.4.8.7

### PR DESCRIPTION
**Pull request by MaticPoh**
In the new version of the tor project, anti DOS protection has been implemented see: https://community.torproject.org/onion-services/advanced/dos/
This is an essential feature

Great project thanks for keeping it going

### CODE REVIEW

**Comment by bugfest** [comment]
Thanks for your contribution @MaticPoh!

**Comment by bugfest** [comment]
Hi @MaticPoh, I've noticed some issues with the PR:
- `tor-0.4.8.7` is not available in Alpine `3.17.3`. This makes the `quick` build fail; so we need to bump Alpine version too.
  - I've just opened a PR to Alpine's aports to get the pow feature enabled there too: https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/54555  
- `pow` is not enabled when building from source; as per the Tor docs, we need to add `--enable-gpl` to the configure script

I got it fixed already; will update this PR when my local multi-arch build finishes (this takes some time)

edit: aports upstream info

**Comment by bugfest** [comment]
Hi @MaticPoh, I don't have edit permissions on your branch so I cannot update this PR myself. I've pushed my changes to https://github.com/bugfest/tor-docker/tree/pr6; would you please rebase/update this PR with my `pr6` branch commits?

Thanks!

**Comment by MaticPoh** [comment]
I merged it with your branch and gave it permission to edit

**Review by bugfest — APPROVED** [review]

**Comment by bugfest** [comment]
Thanks @MaticPoh, PR merged 🎉 !

**Comment by bugfest** [comment]
Build is underway https://github.com/bugfest/tor-docker/actions/runs/6723583571

**Pull request merged**
